### ISSUE TITLE
Completed assignment

### ISSUE THREAD

**Issue by zganunbc** [zganunbc/github-slideshow#2]
@joebottoms I've just completed the part 1 of assignment

**Comment by joebottoms** [comment]
Hi @zganunbc,

It looks like you've opened this issue in the repository for the github training module. As such, I don't see ant_code.R anywhere in here. Could you check that you're pushing your commits to the same repository that you pulled the assignment from? That should hopefully fix this issue and I can add the remaining exercises to your assignment. I'll leave this issue open for now
